"""Initial Migration.

Revision ID: 39045735a84a
Revises: 
Create Date: 2023-03-07 12:00:53.034354

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39045735a84a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student_course',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('grade', sa.String(), nullable=False),
    sa.Column('credit_unit', sa.Float(), nullable=False),
    sa.Column('earned_credit', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.course_id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.student_id'], ),
    sa.PrimaryKeyConstraint('id', 'student_id', 'course_id')
    )
    op.drop_table('student_courses')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student_courses',
    sa.Column('student_id', sa.INTEGER(), nullable=False),
    sa.Column('course_id', sa.INTEGER(), nullable=False),
    sa.Column('grade', sa.VARCHAR(), nullable=False),
    sa.Column('credit_unit', sa.FLOAT(), nullable=False),
    sa.Column('earned_credit', sa.FLOAT(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.course_id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.student_id'], ),
    sa.PrimaryKeyConstraint('student_id', 'course_id')
    )
    op.drop_table('student_course')
    # ### end Alembic commands ###
