"""add gpa to student_course table

Revision ID: 62b9c11b24f8
Revises: 7d33143e7798
Create Date: 2023-03-14 13:42:28.665119

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62b9c11b24f8'
down_revision = '7d33143e7798'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_course', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gpa', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_course', schema=None) as batch_op:
        batch_op.drop_column('gpa')

    # ### end Alembic commands ###
