"""added grades to student_course

Revision ID: 7d33143e7798
Revises: c7c4f31ba50c
Create Date: 2023-03-12 20:50:23.696416

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d33143e7798'
down_revision = 'c7c4f31ba50c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_course', schema=None) as batch_op:
        batch_op.add_column(sa.Column('grade', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_course', schema=None) as batch_op:
        batch_op.drop_column('grade')

    # ### end Alembic commands ###
