"""Updated StudentCourse model

Revision ID: e7b03f3baa34
Revises: 39045735a84a
Create Date: 2023-03-08 10:20:42.651095

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7b03f3baa34'
down_revision = '39045735a84a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_course', schema=None) as batch_op:
        batch_op.drop_column('credit_unit')
        batch_op.drop_column('grade')
        batch_op.drop_column('earned_credit')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_course', schema=None) as batch_op:
        batch_op.add_column(sa.Column('earned_credit', sa.FLOAT(), nullable=False))
        batch_op.add_column(sa.Column('grade', sa.VARCHAR(), nullable=False))
        batch_op.add_column(sa.Column('credit_unit', sa.FLOAT(), nullable=False))

    # ### end Alembic commands ###
